//------------------------------------------------------------------------------
// <auto-generated>
// K53Guru - MIT Licensed.
// Author: neozhu
// CreatedAt/Modified: 2025-07-18
// Validator for ImportContactsCommand: ensures the Data property is non-null and non-empty for contact import.
// Docs: https://docs.cleanarchitectureblazor.com/features/contact
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace K53Guru.Application.Features.Contacts.Commands.Import;

public class ImportContactsCommandValidator : AbstractValidator<ImportContactsCommand>
{
        public ImportContactsCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

