<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>K53Guru.Migrators.SqLite</AssemblyName>
        <RootNamespace>K53Guru.Migrators.SqLite</RootNamespace>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

</Project>